language: go

go:
  - 1.6.1

install:
  - wget https://bitcoin.org/bin/bitcoin-core-0.12.1/bitcoin-0.12.1-linux64.tar.gz -O /tmp/bitcoin.tar.gz
  - tar -xvf /tmp/bitcoin.tar.gz
  - export PATH=$PATH:$(pwd)/bitcoin-0.12.1/bin
  - go get github.com/AutoRoute/bloom
  - go get github.com/AutoRoute/l2
  - go get github.com/AutoRoute/tuntap

script:
  - go test -v ./... -race
