language: go

go:
  - 1.7

install:
  - wget https://bitcoin.org/bin/bitcoin-core-0.13.0/bitcoin-0.13.0-x86_64-linux-gnu.tar.gz -O /tmp/bitcoin.tar.gz
  - tar -xvf /tmp/bitcoin.tar.gz
  - export PATH=$PATH:$(pwd)/bitcoin-0.13.0/bin
  - go get github.com/AutoRoute/bloom
  - go get github.com/AutoRoute/l2
  - go get github.com/AutoRoute/tuntap

script:
  - go test -v ./... -race
